"""empty message

Revision ID: 2757c807da6e
Revises: None
Create Date: 2014-08-06 18:51:54.077000

"""

# revision identifiers, used by Alembic.
revision = '2757c807da6e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
