"""empty message

Revision ID: 17abc82fc72c
Revises: 54185e9c8c99
Create Date: 2014-08-08 20:00:45.250000

"""

# revision identifiers, used by Alembic.
revision = '17abc82fc72c'
down_revision = '54185e9c8c99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
