"""empty message

Revision ID: 3262a3aa37b2
Revises: 2757c807da6e
Create Date: 2014-08-06 19:32:39.648000

"""

# revision identifiers, used by Alembic.
revision = '3262a3aa37b2'
down_revision = '2757c807da6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
